backend:
  name: git-gateway
  branch: main # або master, залежно від вашої гілки за замовчуванням на GitHub
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: img/uploads
public_folder: /img/uploads

collections:
  - name: manga # Назва колекції (для внутрішнього використання)
    label: Manga # Назва колекції, яка відображається в CMS
    folder: data # Папка, де знаходяться файли даних (data/ у вашому випадку)
    create: true # Дозволити створення нових записів
    slug: '{{slug}}' # Шаблон для slug (назви файлу) - можна залишити таким
    format: json # Формат файлів даних - JSON
    fields: # Визначення полів для кожного запису манги
      - { name: title, label: Title, widget: string } # Текстове поле для назви
      - { name: author, label: Author, widget: string, required: false } # Текстове поле для автора (не обов'язкове)
      - { name: coverImage, label: Cover Image URL, widget: image, required: false } # Поле для URL-а зображення обкладинки (віджет "image" для завантаження зображень)
      - { name: synopsis, label: Synopsis, widget: text, required: false } # Багаторядкове текстове поле для синопсису
      - { name: genre, label: Genre, widget: list, required: false } # Поле для списку жанрів (віджет "list" для списку)
      - name: chapterList # Назва поля для списку розділів (для внутрішнього використання)
        label: Chapter List # Назва поля, яка відображається в CMS
        widget: list # Віджет "list" для списку
        fields: # Визначення полів для кожного елементу списку розділів (для кожного розділу)
          - { name: title, label: Chapter Title, widget: string } # Текстове поле для назви розділу
          - { name: content, label: Chapter Content, widget: markdown, required: false } # Багаторядкове текстове поле для контенту розділу (віджет "markdown" для форматування тексту)
      - { name: nowReading, label: Now Reading, widget: boolean, default: false } # Логічний перемикач (checkbox) для "Now Reading"
      - { name: featured, label: Featured, widget: boolean, default: false } # Логічний перемикач (checkbox) для "Featured"